"""
Referral attribution: who brought a user in, and what that is worth.

A referral is two separate events, and they happen at different times on purpose:

* **Attribution** records that a user arrived through a streamer's or a user's
  code. It happens while the row is still being built, *before* it is inserted,
  because `referred_by`/`referred_by_streamer` are columns on the row itself.
* **Settlement** pays the referrer. It happens once, at the moment the referred
  account becomes real — because that is the point at which the referral stops
  being farmable by inventing addresses.

Which moment "real" is depends on the path, and that difference is the whole
reason these are two functions rather than one:

* Password registration is real when the emailed link is consumed, so settlement
  runs from the promotion out of `tempusers`.
* A Google account is real the instant it is created, because Google has already
  verified the address. Waiting for an email that is never sent would mean the
  bonus was never paid at all.

Keeping attribution and settlement apart is what stops a bonus being paid for an
address nobody controls, on the path where that is a risk.
"""

from __future__ import annotations

import logging

from flask import current_app

from constants import TX_BONUS
from credits import add_temp_credits, record_transaction

logger = logging.getLogger(__name__)

# Codes are 8 characters from `string.ascii_letters + string.digits` when
# generated here (see `routes.generate_referral_code`), but streamer codes live
# in a different table and are not generated by this codebase. Bounded and
# alphanumeric so that whatever arrives — a query parameter, a form field, a value
# carried inside an OAuth `state` — can never smuggle anything into a query, a
# log line, or a redirect.
MAX_CODE_LENGTH = 64
_ALLOWED_CHARACTERS = frozenset(
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-"
)


def normalize_code(value) -> str:
    """
    A referral code, or `""` if the input cannot be one.

    Tolerant of surrounding whitespace (a copied code usually carries some) and
    strict about everything else.
    """
    if not isinstance(value, str):
        return ""
    candidate = value.strip()
    if not candidate or len(candidate) > MAX_CODE_LENGTH:
        return ""
    if not all(character in _ALLOWED_CHARACTERS for character in candidate):
        return ""
    return candidate


def resolve(supabase, code: str):
    """
    Turn a code into ``("streamer", id)``, ``("user", id)`` or ``None``.

    Streamers are checked first, and that order is load-bearing: a streamer's code
    lives in `credentials` and must attribute to the streamer's own payout, not to
    an ordinary user who happens to hold a colliding code.
    """
    streamer = (
        supabase.table("credentials").select("streamer_id").eq("id_code", code).execute()
    )
    if streamer.data:
        return ("streamer", streamer.data[0]["streamer_id"])

    referrer = supabase.table("users").select("id").eq("referral_code", code).execute()
    if referrer.data:
        return ("user", referrer.data[0]["id"])

    return None


def attribute(supabase, row: dict, code) -> bool:
    """
    Stamp the referrer onto a row that has not been inserted yet.

    Mutates `row` in place rather than returning the columns, because the caller
    is assembling a row to insert and the attribution is part of it.

    Returns whether the code attributed anything. Never raises: an unrecognised
    code is not a failure, it is a code that attributes nobody, and a signup must
    not be lost because a referral could not be resolved.
    """
    normalized = normalize_code(code)
    if not normalized:
        return False

    try:
        found = resolve(supabase, normalized)
    except Exception as exc:
        logger.error("Could not resolve a referral code: %s", exc)
        return False

    if found is None:
        logger.info("A referral code did not resolve to a streamer or a user.")
        return False

    kind, identifier = found
    if kind == "streamer":
        row["referred_by_streamer"] = identifier
    else:
        row["referred_by"] = identifier
    return True


def settle(supabase, user: dict) -> None:
    """
    Pay the referrer for an account that has just become real.

    The bonus goes to the referrer's **temporary** credits, never to
    `credits_balance`: that is the subscription allowance, owned by Stripe, and
    adding to it would inflate the allowance and drive the usage bar negative.
    Temporary credits are the only correct bucket, and they lapse — a year by
    default, so a referral reads as permanent without becoming a liability that
    never expires.

    A streamer referral holds `referred_by_streamer` and no `referred_by`, so it
    is deliberately not paid here: streamers earn a share of the subscription
    revenue the referred user generates instead, computed in
    `billing._payout_streamers`.

    Best effort throughout. A payout failure must never cost the user their
    account, so every failure is logged and swallowed.
    """
    referrer_id = user.get("referred_by")
    if not referrer_id:
        return

    amount = current_app.config["REFERRAL_BONUS_CREDITS"]
    ttl_days = current_app.config["REFERRAL_BONUS_TTL_DAYS"]

    try:
        # Raises ValueError if the referrer no longer exists.
        add_temp_credits(supabase, referrer_id, amount, ttl_days=ttl_days)

        record_transaction(
            supabase,
            referrer_id,
            amount,
            TX_BONUS,
            f"Referral bonus for {user.get('username') or user.get('email')} "
            f"(expires in {ttl_days} days)",
        )

        logger.info("Awarded %s referral credits to %s", amount, referrer_id)
    except Exception as exc:
        logger.error("Failed to award a referral bonus for %s: %s", user.get("id"), exc)
