import Image from "next/image";

const platforms = [
  { name: "eFootball", text: "Carte, build, rosa e match. Tutto sul tuo gioco.", status: "Disponibile ora", tone: "blue", mark: "e" },
  { name: "Arena Tornei", text: "Community, sfide e tornei in un unico spazio.", status: "Disponibile ora", tone: "violet", mark: "♜" },
  { name: "League of Legends", text: "Coming soon. Ora domina eFootball.", status: "Coming Soon", tone: "slate", mark: "L" }
];
const benefits = ["Carte", "Build", "Rosa", "Match", "Coach"];

export default function Home() {
  return <main className="site-shell">
    <header className="topbar"><a className="brand" href="#top" aria-label="From Zero To Hero home"><Image src="/logo.webp" alt="From Zero To Hero" width={44} height={44} /><span>From Zero To Hero</span></a><nav className="nav" aria-label="Navigazione principale"><a href="#platforms">Piattaforme</a><a href="#how">Come funziona</a><a href="#pricing">Prezzi</a><a href="#faq">FAQ</a></nav><div className="nav-actions"><a className="button ghost" href="/login">Accedi</a><a className="button primary" href="/register">Inizia ora <span aria-hidden>→</span></a></div></header>
    <section className="hero" id="top"><div><div className="eyebrow">GAME PERFORMANCE PLATFORM</div><h1>Un solo accesso.<br /><em>Tutto il tuo ecosistema.</em></h1><p className="hero-copy">Scegli il tuo gioco, trova il prossimo miglioramento e porta ogni partita più vicino al tuo livello.</p><div className="steps"><span className="step"><b>01</b>Accedi</span><span className="step"><b>02</b>Scegli il gioco</span><span className="step"><b>03</b>Migliora</span></div><div className="hero-actions"><a className="button primary" href="/login">Accedi alla piattaforma <span aria-hidden>→</span></a><a className="button ghost" href="#how">▷ &nbsp;Scopri come funziona</a></div></div><div className="hero-platforms" aria-label="Piattaforme dell'ecosistema">{platforms.map((platform) => <article className={`platform-preview ${platform.tone}`} key={platform.name}><div className="preview-mark">{platform.mark}</div><h2>{platform.name}</h2><span className={`pill ${platform.status === "Coming Soon" ? "soon" : ""}`}>{platform.status}</span><p>{platform.text}</p><span className="preview-arrow" aria-hidden>↗</span></article>)}</div></section>
    <section className="section" id="platforms"><div className="section-header"><div><h2>Scegli il tuo gioco</h2><p>eFootball ora, League in arrivo.</p></div><a href="/platforms">Vedi tutte le piattaforme →</a></div><div className="platform-grid">{platforms.map((platform) => <article className={`platform-card ${platform.tone}`} key={platform.name}><header><div className="card-mark">{platform.mark}</div><div><h3>{platform.name}</h3><p>{platform.text}</p></div><span className={`pill ${platform.status === "Coming Soon" ? "soon" : ""}`}>{platform.status}</span></header><span className="card-arrow" aria-hidden>→</span></article>)}</div></section>
    <section className="section" id="how"><div className="benefits">{benefits.map((benefit, index) => <div className="benefit" key={benefit}><b>{String(index + 1).padStart(2, "0")}</b><span><strong>{benefit}</strong><br /><small>{index === 0 ? "spendi solo se serve" : index === 1 ? "fatta per il tuo stile" : index === 2 ? "niente ruoli scoperti" : index === 3 ? "capisci dove perdi campo" : "decisioni pratiche"}</small></span></div>)}</div></section>
    <section className="section" id="pricing"><div className="section-header"><div><h2>Scegli il piano giusto</h2><p>Più valore al tuo gioco. Un unico ecosistema.</p></div><a className="button primary" href="/pricing">Vedi i piani →</a></div><div className="plans"><article className="plan-card"><h3>Scopri l’ecosistema</h3><p>I piani e le condizioni arrivano dal servizio ufficiale.</p><a className="button ghost" href="/pricing">Apri prezzi</a></article><article className="plan-card featured"><h3>Un account, tutti i giochi</h3><p>Accedi una volta e porta il tuo percorso sulle piattaforme disponibili.</p><a className="button primary" href="/register">Inizia ora</a></article><article className="plan-card"><h3>Controllo semplice</h3><p>Profilo, utilizzo e abbonamento in un unico spazio.</p><a className="button ghost" href="/account">Vai al tuo account</a></article></div></section>
    <section className="cta-band" id="faq"><h2>Non copiare. <em>Domina.</em></h2><p>Carica. Analizza. Vinci. Il tuo percorso parte dalla tua rosa.</p><a className="button primary" href="/register">Accedi alla piattaforma →</a></section><footer className="footer"><a className="brand" href="#top"><Image src="/logo.webp" alt="" width={32} height={32} /><span>FROM ZERO TO HERO</span></a><span>Chi siamo　 Lavora con noi　 Termini　 Privacy</span><span>Una piattaforma indipendente ideata e gestita da Spazio Game Srls.</span></footer>
  </main>;
}
