"use client";
import { FormEvent, useMemo, useState } from "react";
import { api, ApiError } from "@/src/lib/api";

export default function ResetPasswordPage() {
  const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false);
  const token = useMemo(() => typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("token") ?? "", []);
  async function submit(event: FormEvent) { event.preventDefault(); if (!token) { setMessage("Il link di reset non è valido o è incompleto."); return; } if (password.length < 8 || password !== confirmation) { setMessage(password.length < 8 ? "La password deve avere almeno 8 caratteri." : "Le password non coincidono."); return; } setBusy(true); setMessage(""); try { await api.resetPassword({ token, password }); setDone(true); setMessage("Password aggiornata. Per sicurezza, tutte le sessioni precedenti sono state chiuse."); } catch (error) { setMessage((error as ApiError).message); } finally { setBusy(false); } }
  return <main className="form-page auth-page"><a className="brand" href="/"><img src="/logo.webp" alt="From Zero To Hero" /><span>From Zero To Hero</span></a><section className="form-card auth-card compact-auth">{done ? <><div className="success-mark" aria-hidden>✓</div><p className="eyebrow">ACCESSO PROTETTO</p><h1>Password aggiornata.</h1><p className="auth-description">{message}</p><a className="button primary" href="/login">Vai all’accesso <span aria-hidden>→</span></a></> : <><div className="auth-card-heading"><p className="eyebrow">SICUREZZA</p><h1>Imposta una nuova password.</h1><p>Usa almeno 8 caratteri e scegli una password che non hai già usato.</p></div><form onSubmit={submit}><label>Password nuova<input type="password" autoComplete="new-password" minLength={8} required value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>Ripeti password<input type="password" autoComplete="new-password" minLength={8} required value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label>{message && <p className="form-error" role="alert">{message}</p>}<button className="button primary" disabled={busy}>{busy ? "Salvataggio…" : "Salva password"}<span aria-hidden>→</span></button></form><a className="form-secondary-link" href="/login">Torna al login</a></>}</section></main>;
}
