"use client";
import { FormEvent, useMemo, useState } from "react";
import { api, ApiError } from "@/src/lib/api";

export default function ResetPasswordPage() {
  const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false);
  const token = useMemo(() => typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("token") ?? "", []);
  async function submit(event: FormEvent) { event.preventDefault(); if (!token) { setMessage("Il link di reset non è valido o è incompleto. · Reset link is invalid or incomplete. · El enlace de restablecimiento no es válido o está incompleto."); return; } if (password.length < 8 || password !== confirmation) { setMessage(password.length < 8 ? "La password deve avere almeno 8 caratteri. · Password must be at least 8 characters. · La contraseña debe tener al menos 8 caracteres." : "Le password non coincidono. · Passwords do not match. · Las contraseñas no coinciden."); return; } setBusy(true); setMessage(""); try { await api.resetPassword({ token, password }); setDone(true); setMessage("Password aggiornata. Per sicurezza, tutte le sessioni precedenti sono state chiuse. · Password updated; previous sessions were signed out. · Contraseña actualizada; se cerraron las sesiones anteriores."); } catch (error) { setMessage(`${(error as ApiError).message} · Password reset failed. · No se pudo restablecer la contraseña.`); } finally { setBusy(false); } }
  return <main className="form-page auth-page"><a className="brand" href="/"><img src="/logo.webp" alt="From Zero To Hero" /><span>From Zero To Hero</span></a><section className="form-card auth-card compact-auth">{done ? <><div className="success-mark" aria-hidden>✓</div><p className="eyebrow">ACCESSO PROTETTO · SECURE ACCESS · ACCESO SEGURO</p><h1>Password aggiornata.</h1><p className="auth-description">{message}</p><a className="button primary" href="/login">Vai all’accesso · Go to sign in · Ir al acceso <span aria-hidden>→</span></a></> : <><div className="auth-card-heading"><p className="eyebrow">SICUREZZA · SECURITY · SEGURIDAD</p><h1>Imposta una nuova password.</h1><p>Usa almeno 8 caratteri e scegli una password che non hai già usato.<br /><span className="muted-inline">Use 8+ characters and avoid a reused password. · Usa 8+ caracteres y evita una contraseña reutilizada.</span></p></div><form onSubmit={submit}><label>Password nuova · New password · Nueva contraseña<input type="password" autoComplete="new-password" minLength={8} required value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>Ripeti password · Repeat password · Repite contraseña<input type="password" autoComplete="new-password" minLength={8} required value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label>{message && <p className="form-error" role="alert">{message}</p>}<button className="button primary" disabled={busy}>{busy ? "Salvataggio… · Saving… · Guardando…" : "Salva password · Save password · Guardar contraseña"}<span aria-hidden>→</span></button></form><a className="form-secondary-link" href="/login">Torna al login · Back to sign in · Volver al acceso</a></>}</section></main>;
}
